# apps/dev/ingress-dev.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-preview
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/csc11007-assignments/spring-pet-clinic-microservices-configuration
    path: ingress/preview
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic-preview
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - PruneLast=true
