apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-common
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/cascade: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/csc11007-assignments/spring-pet-clinic-microservices-configuration
    path: ingress/common
    targetRevision: configure
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - PruneLast=true
