image:
  repository: csc11007/spring-petclinic-config-server
  tag: "8724213"
  pullPolicy: IfNotPresent

replicas: 1

service:
  port: 8888
  type: ClusterIP
  name: config-server

env:
  - name: SPRING_PROFILES_ACTIVE
    value: native, docker
  - name: SPRING_APPLICATION_NAME
    value: CONFIG-SERVER
  - name: SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS
    value: file:/config-data

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

readinessProbe:
  path: /actuator/health
  port: 8888
  initialDelaySeconds: 20
  periodSeconds: 5

livenessProbe:
  path: /actuator/health
  port: 8888
  initialDelaySeconds: 40
  periodSeconds: 10