image:
  repository: csc11007/spring-petclinic-discovery-server
  tag: "f98d5f0"
  pullPolicy: IfNotPresent

replicas: 1

service:
  port: 8761
  type: ClusterIP
  name: discovery-server

env:
  - name: SPRING_PROFILES_ACTIVE
    value: docker
  - name: CONFIG_SERVER_URL
    value: http://config-server:8888

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

readinessProbe:
  path: /actuator/health
  port: 8761
  initialDelaySeconds: 30
  periodSeconds: 10

livenessProbe:
  path: /actuator/health
  port: 8761
  initialDelaySeconds: 60
  periodSeconds: 15