image:
  repository: csc11007/spring-petclinic-discovery-server
  tag: 9e90732
  pullPolicy: IfNotPresent

replicas: 1

service:
  port: 8761
  type: ClusterIP
  name: discovery-server

env:
  - name: SPRING_PROFILES_ACTIVE
    value: docker
  - name: CONFIG_SERVER_URL
    value: http://config-server:8888
  - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
    value: http://discovery-server:8761/eureka/
  - name: EUREKA_INSTANCE_HOSTNAME
    value: discovery-server
  - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
    value: "true"
  - name: EUREKA_CLIENT_FETCH_REGISTRY
    value: "true"
  - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
    value: "false"
  - name: SERVER_PORT
    value: "8761"
  - name: EUREKA_SERVER_ENABLE_SELF_PRESERVATION
    value: "false"
  - name: EUREKA_SERVER_WAIT_TIME_IN_MS_WHEN_SYNC_EMPTY
    value: "0"
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

readinessProbe:
  path: /actuator/health
  port: 8761
  initialDelaySeconds: 30
  periodSeconds: 10

livenessProbe:
  path: /actuator/health
  port: 8761
  initialDelaySeconds: 60
  periodSeconds: 15