image:
  repository: csc11007/spring-petclinic-vets-service
  tag: "1c93882"
  pullPolicy: IfNotPresent

replicas: 1

service:
  port: 8083
  type: ClusterIP
  name: vets-service

env:
  - name: SPRING_PROFILES_ACTIVE
    value: docker
  - name: SPRING_APPLICATION_NAME
    value: VETS-SERVICE
  - name: CONFIG_SERVER_URL
    value: http://config-server:8888
  - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
    value: http://discovery-server:8761/eureka/
  - name: EUREKA_INSTANCE_HOSTNAME
    value: vets-service
  - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
    value: "true"
  - name: EUREKA_CLIENT_FETCH_REGISTRY
    value: "true"
  - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
    value: "false"
  - name: SERVER_PORT
    value: "8083"

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

readinessProbe:
  path: /actuator/health
  port: 8083
  initialDelaySeconds: 30
  periodSeconds: 10

livenessProbe:
  path: /actuator/health
  port: 8083
  initialDelaySeconds: 60
  periodSeconds: 15