apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: visits-service-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: dev
spec:
  project: default
  source:
    repoURL: https://github.com/csc11007-assignments/spring-pet-clinic-microservices-configuration
    path: charts/spring-petclinic-service
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../../values/dev/visits-service_values.yaml
      releaseName: visits-service
  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true