namespace: petclinic-staging
services:
  config-server:
    containerName: config-server
    image: csc11007/spring-petclinic-config-server
    tag: main_v4.0
    port: 8888
  customers-service:
    containerName: customers-service
    image: csc11007/spring-petclinic-customers-service
    tag: main_v4.0
    port: 8081
  discovery-server:
    containerName: discovery-server
    image: csc11007/spring-petclinic-discovery-server
    tag: main_v4.0
    port: 8761
  visits-service:
    containerName: visits-service
    image: csc11007/spring-petclinic-visits-service
    tag: main_v4.0
    port: 8082
  vets-service:
    containerName: vets-service
    image: csc11007/spring-petclinic-vets-service
    tag: main_v4.0
    port: 8083
  genai-service:
    containerName: genai-service
    image: csc11007/spring-petclinic-genai-service
    tag: main_v4.0
    port: 8084
  api-gateway:
    containerName: api-gateway
    image: csc11007/spring-petclinic-api-gateway
    tag: main_v4.0
    port: 8080
    ingress:
      enabled: true
      host: petclinic-staging.com
  admin-server:
    containerName: admin-server
    image: csc11007/spring-petclinic-admin-server
    tag: main_v4.0
    port: 9090
    ingress:
      enabled: true
      host: admin.petclinic-staging.com
  discovery-server-ingress:
    containerName: discovery-server
    image: csc11007/spring-petclinic-discovery-server
    tag: main
    port: 8761
    ingress:
      enabled: true
      host: eureka.petclinic-staging.com
replicaCount: 1
